Fix blocks number calculation for Flat PA
HabanaAI/vllm-fork pull request #269
Opened 2024-09-11 09:48 UTC by iboiko-habana

Fix blocks number calculation for Flat PA via adding empty table_block (https://github.com/HabanaAI/vllm-fork/issues/158)

2024-09-17 05:37 UTC, madamczykhabana requested changes

2024-09-17 05:37 UTC, madamczykhabana commented on vllm/worker/habana_model_runner.py
>                      slot = next(dummy_slots)
Please combine those two if statements. Something like:

```python
if len(block_table) == 0:
    block_number = _PAD_BLOCK_ID
    block_table = []
    slot = next(dummy_slots)
else:
    block_number = block_table[position // self.block_size]
    block_offset = position % self.block_size
    slot = block_number * self.block_size + block_offset
```

2024-09-18 10:08 UTC, madamczykhabana approved these changes
LGTM

2024-09-18 10:09 UTC, merged

2024-09-19 11:06 UTC, hlin99 commented
seq_group_metadata_list.extend(
            self.create_dummy_seq_group_metadata(0, 0, is_prompt)
            for _ in range(batch_size_padding))

this piece of code introduces metadata certation in loop, and observe 10% perf drop. is this code change intentional?

2024-09-20 07:15 UTC, iboiko-habana commented
@hlin99 Thanks. Please re-check perf with https://github.com/HabanaAI/vllm-fork/pull/301

2024-09-20 10:48 UTC, hlin99 commented
> @hlin99 Thanks. Please re-check perf with #301

unfortunately, the perf is not recovered, and perf data looks identical before & after the patch.

i did an experiment as below. the perf could be recovered even if dummy is created each time, but we add seq_group_metadata_list[0] to the list as before. it seems the perf penalty is due to list.extend function.... need further triage

diff --git a/vllm/worker/habana_model_runner.py b/vllm/worker/habana_model_runner.py
index 0d5df1f3..263d55ad 100644
--- a/vllm/worker/habana_model_runner.py
+++ b/vllm/worker/habana_model_runner.py
@@ -1090,7 +1090,7 @@ class HabanaModelRunnerBase(ModelRunnerBase[TModelInputForHPU]):
         if batch_size_padding > 0:
             dummy_seq_group_metadata = self.create_dummy_seq_group_metadata(
                 0, 0, is_prompt)
-            seq_group_metadata_list.extend(dummy_seq_group_metadata
+            seq_group_metadata_list.extend(seq_group_metadata_list[0]
                                            for _ in range(batch_size_padding))

         prefill_reqs = []