Adding compatibility delayed feature sampling and empty block table case
HabanaAI/vllm-fork pull request #306
Opened 2024-09-20 06:51 UTC by iboiko-habana

Add compatibility between feature "delayed sampling" and empty block table case

2024-09-20 07:11 UTC, madamczykhabana requested changes

2024-09-20 07:11 UTC, madamczykhabana commented on vllm/worker/habana_model_runner.py
> +            prev_logits_device = "hpu"
this will break when running on fake_hpu. Perhaps we can take the device from the model or from input_tokens?

2024-09-20 07:11 UTC, madamczykhabana commented on vllm/worker/habana_model_runner.py
> +                                torch.zeros([1, vocab_size],
We could call self.vocab_size here directly instead of introducing a new variable as this value is used only once.

2024-09-20 07:11 UTC, madamczykhabana commented on vllm/worker/habana_model_runner.py
>                              # warmup only, TODO add a check
I guess this comment is no longer needed?

2024-09-23 07:28 UTC, michalkuligowski approved these changes

2024-10-14 07:40 UTC, michalkuligowski commented
Closing as 1.18.0 is closed

2024-10-14 07:40 UTC, closed without merging