Support for long-contexts with LoRA
HabanaAI/vllm-fork pull request #385
Opened 2024-10-11 13:20 UTC by SanjuCSudhakaran

This PR does the following

1. Enable long-context support for LoRA
2. Handle RoPE changes requires for LoRA. The corresponding vllm-hpu-extension changes can be found https://github.com/HabanaAI/vllm-hpu-extension

2024-10-17 09:25 UTC, vivekgoe requested changes
@SanjuCSudhakaran added review comments, please check.

2024-10-17 09:25 UTC, vivekgoe commented on vllm/lora/punica.py
> +    long_lora_offsets_list = []
follow notation, add type List[int]

2024-10-17 09:25 UTC, vivekgoe commented on vllm/lora/punica.py
> +    long_lora_offsets = torch.tensor(long_lora_offsets_list,
W.r.t. functionality this change is ok for other backends (e.g. CUDA) also. @kzawora-intel is it ok to keep it? or do we need to make it HPU specific to be more upstream(ing) friendly?

2024-10-17 09:25 UTC, vivekgoe commented on vllm/lora/layers.py
> +        offsets = self.punica_wrapper.long_lora_indices.reshape_as(positions)
Is this change ok for other backends (e.g. CUDA)?

2024-10-17 09:25 UTC, vivekgoe commented on vllm/lora/layers.py
> +            return (type(source_layer) is HpuLinearScalingRotaryEmbedding
Is there any functional impact of using default code?

2024-10-25 05:06 UTC, SanjuCSudhakaran commented
These changes are no longer required since the latest vllm-fork already refactored RoPE to handle this.

PR https://github.com/HabanaAI/vllm-fork/pull/404

2024-10-25 05:06 UTC, closed without merging