[Doc] Fix broken urls in gaudi-installation
HabanaAI/vllm-fork pull request #473
Opened 2024-11-06 23:06 UTC by MohitIntel

Certain links on the gaudi-installation page which were pointing to docs.habana.ai are broken due to recent re-structuring of docs.habana.ai. This PR fixes those.

2024-11-07 07:35 UTC, michalkuligowski approved these changes

2024-11-07 07:36 UTC, michalkuligowski requested changes
Please update README_GAUDI.md accordingly

2024-11-08 00:25 UTC, MohitIntel commented
@michalkuligowski , Added the same changes to README_GAUDI.md in the latest commit.

2024-11-08 09:26 UTC, michalkuligowski approved these changes

2024-11-08 09:26 UTC, merged