GPTQ Support [Cont.]
HabanaAI/vllm-fork pull request #481
Opened 2024-11-08 22:38 UTC by maktukmak

This PR enables loading GPTQ quantized models and running weight-only quantized inference on HPU. For a previous discussion, see #421.

2024-11-13 07:55 UTC, michalkuligowski requested changes

2024-11-13 07:55 UTC, michalkuligowski commented on vllm/_custom_ops.py
> +    import habana_frameworks.torch.core as htcore
Why is this import needed?

2024-12-02 06:29 UTC, maktukmak reviewed
Not needed anymore. Removed.

2024-12-11 14:45 UTC, michalkuligowski commented
Awaiting legal input on licensing

2025-01-15 08:54 UTC, michalkuligowski requested changes

2025-01-15 08:54 UTC, michalkuligowski commented on vllm/model_executor/layers/linear.py
> +    "TPUInt8LinearMethod", "GPTQLinearMethod", "GPTQHPULinearMethod", "FBGEMMFp8LinearMethod",
Classes in extensions are now approved, please fix conflicts in this PR.

2025-01-15 08:54 UTC, michalkuligowski commented on vllm/model_executor/layers/quantization/__init__.py
>      NeuronQuantConfig)
Make sure that after vllm-hpu-extensions GPTQ class is merged to update sha in requirements-hpu.txt

2025-01-15 22:58 UTC, maktukmak commented on vllm/model_executor/layers/linear.py
> +    "TPUInt8LinearMethod", "GPTQLinearMethod", "GPTQHPULinearMethod", "FBGEMMFp8LinearMethod",
Fixed conflicts by rebasing

2025-01-15 22:58 UTC, maktukmak commented on vllm/model_executor/layers/quantization/__init__.py
>      NeuronQuantConfig)
Will do once extension PR is merged.

2025-01-16 08:19 UTC, michalkuligowski commented on vllm/model_executor/layers/quantization/__init__.py
>      NeuronQuantConfig)
Please update sha in requirement-hpu.txt to 47c75aa  for tests to pass

2025-01-17 09:28 UTC, michalkuligowski requested changes
Please fix yapf/ruff issues

2025-01-17 18:55 UTC, maktukmak commented
Fixed formatting with running format.sh

2025-01-20 07:40 UTC, michalkuligowski requested changes

2025-01-20 07:40 UTC, michalkuligowski commented on vllm/model_executor/layers/linear.py
> +    "TPUInt8LinearMethod", "GPTQLinearMethod", "GPTQHPULinearMethod",
Please fix conflicts

2025-01-21 19:48 UTC, maktukmak commented on vllm/model_executor/layers/linear.py
> +    "TPUInt8LinearMethod", "GPTQLinearMethod", "GPTQHPULinearMethod",
Resolved

2025-01-29 07:36 UTC, michalkuligowski requested changes

2025-01-29 07:36 UTC, michalkuligowski commented on tests/quantization/test_gptq.py
> +def test_gptq(vllm_runner, model, dtype):
Please add invocation of this UT in:
`.jenkins/test_config.yaml`

2025-01-30 09:05 UTC, michalkuligowski approved these changes

2025-01-30 09:09 UTC, merged