Resolved ALIBI bias regression due to porting flat PA
HabanaAI/vllm-fork pull request #503
Opened 2024-11-15 05:44 UTC by tannervoas742

**Requires associated changes on [vllm-fork PR](https://github.com/HabanaAI/vllm-hpu-extension/pull/34)**

**NOTE:** A recent change on habana_main (https://github.com/HabanaAI/vllm-fork/commit/c27899a0ae694ccdd2bc65a5e86e97d7ec48bccb and https://github.com/HabanaAI/vllm-fork/commit/eca9a83a2d6d60d4c5f577a993e1a95cd64d6a59) changed similar sections of code. I will need to look at those changes and rebase this PR.

This PR makes changes to the way block_mapping, block_usage, and block_list is computed to fix issues in attention computation. As far as I can tell, the issues that are fixed here are not unique to ALiBI.

Additional pre-computes ALiBI blocks and passes it to the attention implementation where its merged with the slopes.

In my testing this PR fully restores functionality for models which require ALiBI biases.

2024-12-05 19:34 UTC, tannervoas742 commented
@itaraban @madamczykhabana @kzawora-intel has anyone gotten a chance to review this PR and the associated one on [vllm-hpu-extension](https://github.com/HabanaAI/vllm-hpu-extension/pull/34). I just pushed out a significant update that minimizes changes to non-alibi code sections. It also has significant accuracy and memory optimization changes.

With the current changes ALiBi is now fully functional as long as FW >= 1.19.0 is being used.

Please help review. Any feedback would be appreciated.

2024-12-12 10:56 UTC, itaraban approved these changes

2024-12-12 11:08 UTC, michalkuligowski requested changes

2024-12-12 11:08 UTC, michalkuligowski commented on vllm/worker/hpu_model_runner.py
> +        # Create intermediary and output strctures
Please fix typo as per static code analisys.

2024-12-12 11:08 UTC, michalkuligowski commented on vllm/attention/backends/hpu_attn.py
>          kv_cache_dtype: str,
please modify requirements-hpu.txt to point to apropriate vllm-hpu-extension commit (0766759), fix static code analisys issues and we can merge

2024-12-12 20:09 UTC, tannervoas742 commented
@michalkuligowski I have fixed the static code analysis issue as well as updated requirements-hpu.txt

2024-12-13 08:32 UTC, michalkuligowski approved these changes

2024-12-13 09:44 UTC, michalkuligowski requested changes
@tannervoas742  there are still some issues detected, please check (you can try runing format.sh script):
Error: vllm/attention/layer.py:99: error: Too many arguments for "AttentionImpl"  [call-arg]
Error: vllm/attention/backends/hpu_attn.py:279: error: Value of type "Optional[Any]" is not indexable  [index]
Error: vllm/attention/backends/hpu_attn.py:291: error: Item "None" of "Optional[Any]" has no attribute "unsqueeze"  [union-attr]

2024-12-13 17:59 UTC, tannervoas742 commented
@michalkuligowski I see the issues now. I wasn't sure where to view the static code analysis report, but found it. I pushed out an update. Waiting for the code analysis to run again. Will reply here when it's finished and ready for re-review.

2024-12-17 02:11 UTC, tannervoas742 commented
@itaraban @michalkuligowski I have updated the PR and ran the script in tools/mypy.sh which passes locally. I also tested the updated version with various ALiBi and non-alibi models. Please re-review. I opened the extension PR again as well. https://github.com/HabanaAI/vllm-hpu-extension/pull/60

2025-01-09 15:54 UTC, kwisniewski98 requested changes
The biggest issue I have right now is that modifying any file that isn't hpu specific (models, attention backends) will cause it to be hard/impossible to upstream. I didn't want to repeat comment for each file, but I think that changes should be removed from all of them.

2025-01-09 15:54 UTC, kwisniewski98 commented on vllm/worker/hpu_model_runner.py
> +            alibi_blocks = alibi_blocks.to(  # type: ignore
Can't we just create tensors on specific devices instead of doing `.to`? I think that this can cause graph breaks in lazy, but I might be wrong

2025-01-13 03:38 UTC, tannervoas742 commented on vllm/worker/hpu_model_runner.py
> +            alibi_blocks = alibi_blocks.to(  # type: ignore
This format is used in later code sections (about 20 lines down). I believe the goal is to compute the structures on the CPU and then asynchronously move to HPU. The exact commit this format was adopted is here. https://github.com/HabanaAI/vllm-fork/commit/7c5038cc0e88b8e2ea027c9f2be4845c2a7f67ad

2025-01-13 03:40 UTC, tannervoas742 commented on vllm/model_executor/models/baichuan.py
> +        self.use_alibi = position_embedding == "ALIBI"
I was unaware we are not able to make any modifications to even the model definitions. This will be very hard to implement the optimizations (layer sharing) that have been implemented here.

As for this use_alibi is used in hpu_model_runner.py to determine if alibi_blocks are needed or not.

I can remove these changes from the model definitions and move them to hpu_model_runner.py, but doing so there will be more tedious. I understand why we want to avoid modifying non-hpu files though.

2025-01-14 03:52 UTC, tannervoas742 commented
@kwisniewski98 I refined this PR with only hpu files being changed. I also have rebased this and the extension PR (https://github.com/HabanaAI/vllm-hpu-extension/pull/60) off the latests mains. Tested with several ALiBi and non-alibi models. And local mypy runs showed no new mypy errors.

Please help re-review.

2025-01-14 13:40 UTC, kwisniewski98 reviewed
Just last small comment. We will merge https://github.com/HabanaAI/vllm-hpu-extension/pull/70 probably tomorrow, after that you will have to change sha of vllm-hpu-extension in requirements-hpu.txt

2025-01-14 13:40 UTC, kwisniewski98 commented on vllm/attention/backends/hpu_attn.py
> +        self.max_seq_len_upper = int(
I don't think that this variable has to be object's field. Please remove `self.`

2025-01-14 14:19 UTC, tannervoas742 commented
> Just last small comment. We will merge [HabanaAI/vllm-hpu-extension#70](https://github.com/HabanaAI/vllm-hpu-extension/pull/70) probably tomorrow, after that you will have to change sha of vllm-hpu-extension in requirements-hpu.txt

Understood. I fixed the small issue you mentioned. Will update this PR with the extension sha after that has merged.

2025-01-20 13:14 UTC, michalkuligowski requested changes
Please fix the conflicts and static code analisys issues

2025-01-20 13:33 UTC, tannervoas742 commented
@michalkuligowski @kwisniewski98 conflicts have been resolved. Yapf and ruff issues should also be resolved now.

2025-01-27 12:54 UTC, mswiniarsk commented on vllm/attention/backends/hpu_attn.py
> +                            position_bias = self.prompt_position_bias[:, :,
It is hardly readable, could you please format the line?

2025-01-27 15:06 UTC, tannervoas742 commented on vllm/attention/backends/hpu_attn.py
> +                            position_bias = self.prompt_position_bias[:, :,
This is how yapf formatted it. I had it formatted differently but then yapf CI was failing since it was suggesting this reformat. I also don't like this format but I applied the yapf patch to resolve the CI failures.

2025-02-05 09:00 UTC, mswiniarsk approved these changes

2025-02-05 12:47 UTC, PatrykWo commented
@kwisniewski98 please resolve conflicts before merge.

2025-02-05 15:47 UTC, tannervoas742 commented
> @kwisniewski98 please resolve conflicts before merge, plus some tests failed.

Resolved merge conflicts. Waiting for tests to re-run.

2025-02-06 08:58 UTC, kwisniewski98 approved these changes

2025-02-06 10:04 UTC, tannervoas742 commented
> @tannervoas742 Could you please switch for now vllm-hpu-extension version to branch that you've added to check if tests will go through?

Updated the reference. The cpu-test passed when I ran it locally.

2025-02-10 10:56 UTC, PatrykWo commented
@tannervoas742 please resolve issue in yapf

yapf.....................................................................Failed
- hook id: yapf
- exit code: 1

2025-02-10 14:08 UTC, tannervoas742 commented
> @tannervoas742 please resolve issue in yapf
> 
> yapf.....................................................................Failed
> 
> * hook id: yapf
> * exit code: 1

Fixed. I setup my pre-commit hooks locally and they passed now including yapf.

2025-02-13 11:47 UTC, tannervoas742 commented
> @tannervoas742 please rebase

Rebased

2025-02-21 03:06 UTC, tannervoas742 commented
Freshly rebased. ALiBi fixes still work. Pre-commit hooks all passed.

2025-03-04 10:35 UTC, PatrykWo commented
@tannervoas742 please resolve conflict.

2025-03-04 10:43 UTC, tannervoas742 commented
> @tannervoas742 please resolve conflict.

Resolved conflicts in this and the extension change.

2025-03-05 01:22 UTC, tannervoas742 commented on requirements-hpu.txt
> +vllm-hpu-extension @ git+https://github.com/tannervoas742/vllm-hpu-extension.git@restore_alibi_for_flat_pa_final
Im aware. I will update this PR as soon as the extension merges.

2025-03-07 12:46 UTC, kwisniewski98 commented
@tannervoas742 hpu extension PR was merged, please change `requirements-hpu.txt`

2025-03-07 13:40 UTC, tannervoas742 commented
> @tannervoas742 hpu extension PR was merged, please change `requirements-hpu.txt`

Conflicts resolved and extension reference was updated.

2025-03-07 18:22 UTC, michalkuligowski approved these changes

2025-03-11 14:56 UTC, merged