[BUG_FIX] 405B WARMUP failed on "FATAL ERROR :: MODULE:PT_LAZY Error, ValidateSyncInputTensors tensor_data is empty"
HabanaAI/vllm-fork pull request #529
Opened 2024-11-20 21:19 UTC by xuechendi

Fix an error report when warming up 405B model

==== Background ====
Mlperf team met this error when running 405B FP8 model on 8cards G2, due to insufficient device memory, last bucket got a faulty size as 2862, which is N * block_size and did not round up.
This later triggers an error that fetched K, V can not apply with block_bias.
```
block_bias shape is [3072, 128]
key is fetched based on block_list and shape is [2862, 128, ...]
```

FIX #xxxx (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ https://docs.vllm.ai/en/latest/contributing/overview.html **

2024-11-20 21:21 UTC, xuechendi commented
@mfylcek @madamczykhabana, please take a look of this fix
I noticed the round_up for last bucket is removed in ContinuousPA pr, any special reason for that?

I tested 405B-fp8 with current fix, warm up can be completed successfully with correct inference result.

2024-11-21 06:21 UTC, madamczykhabana commented
Previously you could gather more blocks than you actually have. With contiguous pa that's not possible as we can't create a slice that's bigger then whole kv-cache.
What bothers me is why block_usage (which is used to create block_bias) is rounded...

2024-11-21 06:22 UTC, madamczykhabana requested changes
We cannot change it this way. We need to figure out why there's this shape mismatch between block_usage and number of blocks

2024-11-21 06:31 UTC, madamczykhabana commented
@mfylcek could you please take a quick look at it?

2024-11-21 13:15 UTC, mfylcek commented
I'm working on the fix

2024-11-21 16:21 UTC, mfylcek commented
I think this issue will appear not just in warmup, but each time the number of utilized blocks gets close to the limit. Quickest WA is https://github.com/HabanaAI/vllm-fork/blob/8768f17480ca21e23b56f02fdc3012ba3eb3342c/vllm/worker/hpu_model_runner.py#L1103

2024-11-21 16:26 UTC, xuechendi commented
@mfylcek, I see, however, hitting limit of number of utilized blocks will be rarer to happen because people might actually do small seq_len test but start the serving_process with long seq_len, ex: --max-model-len 16384

2024-11-25 08:37 UTC, michalkuligowski commented
#532 is merged, please test, closing this PR

2024-11-25 08:37 UTC, closed without merging