revert requirements-hpu.txt for 1.19, add tmp one for 1.18
HabanaAI/vllm-fork pull request #547
Opened 2024-11-26 03:53 UTC by xuechendi

Fix 1.19 INC incompatible issues

https://jira.habana-labs.com/browse/SW-209688

FIX #xxxx (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ https://docs.vllm.ai/en/latest/contributing/overview.html **

2024-11-26 09:59 UTC, michalkuligowski requested changes
Lets not confuse users with adding new requirements file

2024-11-27 14:49 UTC, michalkuligowski requested changes

2024-11-27 14:49 UTC, michalkuligowski commented on requirements-hpu.txt
> -neural-compressor @ git+https://github.com/intel/neural-compressor.git@b196432
Approved

2024-11-27 14:49 UTC, michalkuligowski commented on requirements-hpu-1.18.txt
> +# Common dependencies
Lets not add this, there is description in issues and release notes on how to handle this issue.

2024-12-02 15:58 UTC, michalkuligowski approved these changes

2024-12-05 08:11 UTC, michalkuligowski commented
@xuechendi please resolve conflict

2024-12-05 15:32 UTC, xuechendi commented
@michalkuligowski , conflict resolved.

2024-12-06 11:25 UTC, merged