Add exponential bucketing integration
HabanaAI/vllm-fork pull request #642
Opened 2024-12-17 14:52 UTC by kzawora-intel

Requires https://github.com/HabanaAI/vllm-hpu-extension/pull/61

2025-01-29 21:13 UTC, michalkuligowski requested changes

2025-01-29 21:13 UTC, michalkuligowski commented on vllm/core/scheduler.py
> +            'VLLM_EXPONENTIAL_BUCKETING', 'true').lower() == 'true'
Shall this variable be defined in manual?

2025-03-27 17:55 UTC, kzawora-intel commented
/run-gaudi-tests

2025-03-28 12:03 UTC, madamczykhabana submitted a review, later dismissed

2025-03-28 12:03 UTC, madamczykhabana commented on vllm/worker/hpu_worker.py
> +            self.model_runner.bucketing_ctx.generate_prompt_buckets()
why we need to explicitly call this here? It should've been initialized in runner constructor

2025-04-07 16:00 UTC, kzawora-intel commented
/run-gaudi-tests

2025-04-09 13:51 UTC, iboiko-habana commented
/run-gaudi-tests

2025-04-09 13:51 UTC, iboiko-habana commented
/run-gaudi-tests

2025-04-09 14:28 UTC, iboiko-habana commented
/run-gaudi-tests

2025-04-10 17:47 UTC, kzawora-intel commented
/run-gaudi-tests

2025-04-11 12:37 UTC, kzawora-intel commented
/run-gaudi-tests

2025-04-11 13:02 UTC, kzawora-intel commented
/run-gaudi-tests

2025-04-11 13:12 UTC, kzawora-intel commented
/run-gaudi-tests

2025-04-11 13:19 UTC, kzawora-intel commented
/run-gaudi-tests

2025-04-11 14:31 UTC, merged