Add mark_step for encoder layers
HabanaAI/vllm-fork pull request #650
Opened 2024-12-19 08:31 UTC by yisonzhu

Coupled with [PR620](https://github.com/HabanaAI/vllm-fork/pull/620)[Use FusedSDPA for MllamaVisionSdpaAttention #620], these two issues can be solved:
1. Running llama3.2 vision model on Gaudi3 with batchsize greater than 1 causes GC fail.
2. Using torch2.5 consumes much more device memory than torch2.4 when running llama3.2 vision model.

2024-12-20 14:19 UTC, jkaniecki approved these changes
LGTM

2025-01-07 09:27 UTC, michalkuligowski requested changes

2025-01-07 09:27 UTC, michalkuligowski commented on vllm/worker/hpu_model_runner.py
> +def get_target_layer_suffix(model_type) -> list[str]:
Please change to something like "get_target_layer_suffix_list" to reflect return type

2025-01-07 09:27 UTC, michalkuligowski commented on vllm/worker/hpu_model_runner.py
> +                        suffix: list[str],
Please change to something like "suffix_list" to reflect the underlying type

2025-01-08 03:29 UTC, yma11 commented
Hi @michalkuligowski, thanks for your review but I need to create a new PR https://github.com/HabanaAI/vllm-fork/pull/669 to address your comments. Can you help close this one and take a look at the new one?

2025-01-08 09:02 UTC, closed without merging