Chunked Prefill
HabanaAI/vllm-fork pull request #656
Opened 2024-12-20 06:16 UTC by hlahkar

FILL IN THE PR DESCRIPTION HERE

FIX #xxxx (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ https://docs.vllm.ai/en/latest/contributing/overview.html **

This is a WIP; with the initial changes for Chunked Prefill Functionality. Please do not merge

2025-02-27 08:33 UTC, madamczykhabana requested changes

2025-02-27 08:33 UTC, madamczykhabana commented on tests/basic_correctness/test_chunked_prefill.py
I don't think we should modify the test cases or at least add special case support for HPU.

@kzawora-intel what's the guideline around modifying test cases? Is this something we can do, we should avoid or any other option?

2025-02-27 08:33 UTC, madamczykhabana commented on vllm/attention/backends/hpu_attn.py
> +    chunk_prefill_enabled: bool = False
The number of tensors in that dataclass is getting out of hand :(

2025-02-27 08:33 UTC, madamczykhabana commented on vllm/attention/backends/hpu_attn.py
> +    def forward_chunked_prefill(
This function is huge and really hard to follow. Please split it up into smaller parts. Perhaps some of the logic can be reused from existing implementations.

2025-02-27 08:33 UTC, madamczykhabana commented on vllm/attention/backends/hpu_attn.py
> +                        attn_bias = torch.cat((single_attn_bias, attn_bias), dim=0)
This might be slow both in runtime and compilation times. For example there are scenarios where we use batch_size > 640 . Additionally recalculating attn_bias for each layer can take a significant portion of time.

2025-02-27 08:33 UTC, madamczykhabana commented on vllm/engine/arg_utils.py
> +    use_padding_aware_scheduling: bool = True
We shouldn't change the default for other platforms

2025-02-27 08:33 UTC, madamczykhabana commented on vllm/model_executor/sampling_metadata.py
> +            query_len = 1
Is it ok to always use 1?

2025-02-27 08:33 UTC, madamczykhabana commented on vllm/worker/hpu_model_runner.py
Adding some much duplicated code will be a huge maintenance burden. We need to figure out a better way to structure the code and reuse as much as possible

2025-02-27 08:55 UTC, kzawora-intel commented on vllm/attention/backends/hpu_attn.py
> +                )
In chunked prefill it is possible that a request gets split across engine iterations, e.g. for 1024 tokens, you might need to compute the first 512 in the first iteration, and the remaining 512 in second with prefix prefill. Does this handle that scenario properly?

2025-02-28 07:30 UTC, darekkreft commented
@hlahkar I tested throughput_llama3_1_8b_128_128-bf16-1x-perf-vllm-g2-chunked-prefill with commit e29c70e6af9d9432f4126772791a881cdf7f35fe. Look this functionality not works functional yet.
From server got:

 IndexError: tuple index out of range, log ->[log]( https://qa-jenkins-ctrl03.habana-labs.com/job/qa_jobs/job/qa_testers/job/gdn-qa/job/pytorch/job/gaudi2/job/archived/job/VLLM/job/continous_batching/job/NVIDIA_like_benchmarks/job/chunked_prefill/job/on_demand_throughput_llama3_1_8b_128_128-bf16-1x-perf-vllm-g2-chunked-prefill_pytorch_gaudi2-ak8s_master/9/artifact/vllm_server.log)

From pytorch_log.txt ->[log](https://qa-jenkins-ctrl03.habana-labs.com/job/qa_jobs/job/qa_testers/job/gdn-qa/job/pytorch/job/gaudi2/job/archived/job/VLLM/job/continous_batching/job/NVIDIA_like_benchmarks/job/chunked_prefill/job/on_demand_throughput_llama3_1_8b_128_128-bf16-1x-perf-vllm-g2-chunked-prefill_pytorch_gaudi2-ak8s_master/9/artifact/habana_logs/pytorch_log.txt)

td::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)+0x2d) [0x7f118f8ade1d]
[19:39:46.404082][PT_BRIDGE       ][error][tid:1BCE] /lib/x86_64-linux-gnu/libc.so.6(+0x99ee8) [0x7f1232538ee8]

2025-03-07 12:04 UTC, hlahkar commented on tests/basic_correctness/test_chunked_prefill.py
@madamczykhabana I have added a new file for our test case; keeping the original test case as it is.

2025-03-07 12:06 UTC, hlahkar commented on vllm/attention/backends/hpu_attn.py
> +    def forward_chunked_prefill(
@madamczykhabana This function I have  refactored into 2; one for the preprocessing and the second one for the actual attention. Please check once

2025-03-07 12:07 UTC, hlahkar commented on vllm/attention/backends/hpu_attn.py
> +                        attn_bias = torch.cat((single_attn_bias, attn_bias), dim=0)
set_attn_bias has been moed to hpu_model_runner; and is now calculated only once per batch

2025-03-07 12:07 UTC, hlahkar commented on vllm/model_executor/sampling_metadata.py
> +            query_len = 1
This code went in by mistake; and has been reverted.

2025-03-07 12:10 UTC, hlahkar commented on vllm/worker/hpu_model_runner.py
Most of the duplicate code has been removed. Kindl check

2025-03-07 12:10 UTC, hlahkar commented on vllm/attention/backends/hpu_attn.py
> +                )
Since we are passing the attention_bias; it is taken care of

2025-03-07 12:11 UTC, hlahkar commented on vllm/attention/backends/hpu_attn.py
> +    chunk_prefill_enabled: bool = False
I understand this; but unfortunately we need this information for mixed batches

2025-03-14 11:13 UTC, michalkuligowski requested changes

2025-03-14 11:13 UTC, michalkuligowski commented on tests/basic_correctness/test_chunked_prefill_hpu.py
> +"""Compare the outputs of HF and vLLM when using greedy sampling.
Please fix precommit issues.
Are those tests that @darekkreft  mentioned working now?

2025-03-16 13:06 UTC, hlahkar commented on tests/basic_correctness/test_chunked_prefill_hpu.py
> +"""Compare the outputs of HF and vLLM when using greedy sampling.
All the precommit issues are solved and UT cases are passing. We are working on the issue mentioned by @darekkreft

2025-03-28 13:05 UTC, closed without merging

2025-03-28 13:05 UTC, hlahkar commented
As we are not taking this version of chunked prefill, closing this